all:
  children:
    windows:
      children:
        windows_2025:
        windows_2022:
        windows_2019:
        windows_core:
        windows_gui:
      vars:
        ansible_connection: psrp
        ansible_psrp_auth: kerberos
        ansible_psrp_protocol: https
        ansible_psrp_cert_validation: ignore

    windows_2025:
      hosts:
        w25c-test001.ds.sal9000.tech:
        w25g-test001.ds.sal9000.tech:

    windows_2022:
      hosts:
        w22c-test001.ds.sal9000.tech:
        w22g-test001.ds.sal9000.tech:

    windows_2019:
      hosts:
        w19c-test001.ds.sal9000.tech:
        w19g-test001.ds.sal9000.tech:

    windows_core:
      hosts:
        w25c-test001.ds.sal9000.tech:
        w22c-test001.ds.sal9000.tech:
        w19c-test001.ds.sal9000.tech:

    windows_gui:
      hosts:
        w25g-test001.ds.sal9000.tech:
        w22g-test001.ds.sal9000.tech:
        w19g-test001.ds.sal9000.tech:
